Repository InftyAI/Awesome-LLMOps, pull requests merged in 2024-06, with the labels that each got.

#18 fix owners
  .github/workflows/kube-actions.yaml
Labels: lgtm, cleanup

#20 remove-kind command support
  .github/workflows/kube-actions.yaml
Labels: lgtm, cleanup

#19 fix owners
  OWNERS
Labels: lgtm, approved, cleanup, feature

#24 trim \n
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved, cleanup

#25 debug
  .github/workflows/kube-actions.yaml
  .gitignore
Labels: lgtm, approved

#26 debug
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved, cleanup

#27 add hold
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved, cleanup, feature

#28 refactor
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#30 add token
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved, cleanup

#31 Use one job to avoid failures
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#32 Add LMDeploy
  .github/workflows/kube-actions.yaml
  README.md
Labels: lgtm, approved

#33 remove lgtm when new push
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#34 test forch push
  .github/workflows/kube-actions.yaml
  .gitignore
  README.md
Labels: lgtm, approved

#35 test forch push
  .github/workflows/kube-actions.yaml
  .gitignore
Labels: lgtm, do-not-merge/hold

#37 fix
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved, cleanup

#38 e
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#39 fix
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#43 fix
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#51 watch unlabeled
  .github/workflows/kube-actions.yaml
Labels: lgtm, approved

#55 fix addlabel to issue
  .github/workflows/kube-actions.yaml
Labels: cleanup

#57 test
  .github/workflows/kube-actions.yaml
  OWNERS
Labels: lgtm

#59 fix typo
  .github/workflows/kube-actions.yaml
Labels: lgtm, do-not-merge/hold

#60 Trigger merge when label updated
  .github/workflows/kube-actions.yaml
  OWNERS
Labels: lgtm, approved, cleanup

#62 test
  .github/workflows/kube-workflow.yaml
Labels: lgtm, approved, cleanup

#64 test
  .github/workflows/kube-workflow.yaml
  OWNERS
Labels: feature

#65 test
  .github/workflows/kube-workflow.yaml
Labels: lgtm, cleanup

#68 Add Haystack to LLMOps
  README.md
Labels: lgtm, approved, feature

#69 Add lm-evaluation-harness to Evaluation
  README.md
Labels: lgtm, approved, feature
