Repository InftyAI/Awesome-LLMOps, pull requests merged in 2025-04, with the labels that each got.

#128 Add opik as evaluation project
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#129 Add benchmark
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#130 Add Graphiti
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#131 add cline MCP Marketplace
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#132 Add cr7258 as the reviewer
  OWNERS
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#133 Add OpenAI Codex
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#134 Add vercel AI chat sdk
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#136 Add script and github action to quickly add new projects
  .github/ISSUE_TEMPLATE/REQUEST.md
  .github/workflows/project-request.yaml
  project_request.py
  requirements.txt
Labels: lgtm, approved, feature, needs-priority, needs-triage

#140 Add agent token
  .github/workflows/project-request.yaml
  README.md
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#142 Use octokit
  .github/workflows/project-request.yaml
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#145 Add adk-python to Framework
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#147 Add Higress MCP marketplace
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#149 Add langfuse to Application Orchestration Framework
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#150 Update README & add issue creator as the co-author
  .github/workflows/project-request.yaml
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#158 Add BaiLian MCP and ModelScope MCP
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#157 Add dlrover to Training
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#155 feat(website): support project website built with landscape tools
  .github/workflows/landscape.yml
  .gitignore
  Makefile
  website/README.md
  website/data.yml
  website/guide.yml
  website/logos/agent-development-kit.png
  website/logos/agno.svg
  website/logos/awesome-llmops-dark.svg
  website/logos/awesome-llmops-light.svg
  website/logos/browser-use.png
  website/logos/llmops.png
  website/logos/openRLHF.png
  website/settings.yml
Labels: lgtm, approved, feature, needs-priority, needs-triage

#160 Add mcpmarket.com to MCP Servers.
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#165 Add Docker MCP Catalog
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#167 Add suna to Framework
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#169 nominate cr7258 to Approver
  OWNERS
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#168 Add E2B and Daytona to Development Environment category
  .github/ISSUE_TEMPLATE/REQUEST.md
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#170 Update the Categories
  website/guide.yml
Labels: lgtm, approved, feature, needs-priority, needs-triage

#171 Update data.yaml & Readme.md & CI workflow
  .github/ISSUE_TEMPLATE/REQUEST.md
  README.md
  website/README.md
  website/data.yml
  website/settings.yml
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#172 Add projects
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
  README.md
  website/data.yml
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#173 Update README.md to correct section title and reorder AI Gateway entry
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#174 Change category for some projects
  README.md
  website/data.yml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#175 added logo and updated websites of Inference Platform and AI Gateway
  website/data.yml
  website/logos/aibrix.jpeg
  website/logos/apisix.png
  website/logos/envoy-ai-gateway.png
  website/logos/gateway-api-inference-extension.png
  website/logos/higress.avif
  website/logos/kaito.png
  website/logos/kgateway.png
  website/logos/kong.png
  website/logos/kserve.png
  website/logos/kubeai.png
  website/logos/llmaz.png
  website/logos/lmcache.png
  website/logos/mooncake.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#177 Add agent logos
  website/data.yml
  website/logos/autogppt.png
  website/logos/autogpt.png
  website/logos/camel.png
  website/logos/kagent.svg
  website/logos/langchain.svg
  website/logos/langgraph.png
  website/logos/lightrag.png
  website/logos/llamaindex.svg
  website/logos/openai.png
  website/logos/openmanus.png
  website/logos/pydanticai.svg
  website/logos/semantickernel.png
  website/logos/suna.svg
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#179 Add workflow logos
  website/data.yml
  website/logos/berriai.png
  website/logos/deepset.png
  website/logos/dify.png
  website/logos/flowiseai.png
  website/logos/k8s.png
  website/logos/lmsys.png
  website/logos/portkeyai.png
  website/logos/roboflow.png
Labels: lgtm, approved, feature, needs-priority, needs-triage

#180 Update llmaz logo
  website/data.yml
  website/logos/llmaz.png
  website/logos/llmaz1.svg
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#181 Rename llmaz1.svg to llmaz.svg
  website/logos/llmaz.svg
Labels: lgtm, approved, cleanup, needs-priority, needs-triage
