Repository InftyAI/Awesome-LLMOps, pull requests merged in 2025-05, with the labels that each got.

#182 Add all logos
  website/data.yml
  website/logos/5ire.png
  website/logos/agentbench.png
  website/logos/auto-dev.png
  website/logos/axolotl.svg
  website/logos/cherry-studio.png
  website/logos/chroma.png
  website/logos/codefuse.png
  website/logos/cody.png
  website/logos/colossalai.png
  website/logos/continue.png
  website/logos/daytona.png
  website/logos/deeplake.png
  website/logos/dlrover.png
  website/logos/e2b.png
  website/logos/eleutherai.png
  website/logos/flyte.png
  website/logos/google.png
  website/logos/gradio.png
  website/logos/helicone.png
  website/logos/jan.png
  website/logos/kubeflow.png
  website/logos/langfuse.png
  website/logos/llamafactory.png
  website/logos/lmflow.png
  website/logos/lobe-chat.png
  website/logos/longbench.png
  website/logos/ludwig.png
  website/logos/meta.png
  website/logos/metaflow.png
  website/logos/milvus.png
  website/logos/mlflow.png
  website/logos/mlx.png
  website/logos/nextchat.png
  website/logos/open-webui.png
  website/logos/opencompass.svg
  website/logos/openllmetry.png
  website/logos/opik.png
  website/logos/phoenix.png
  website/logos/polyaxon.png
  website/logos/privategpt.png
  website/logos/ray.png
  website/logos/seldon-core.png
  website/logos/selfrlhf.png
  website/logos/sweep.png
  website/logos/swift.png
  website/logos/tabby.png
  website/logos/torchtune.png
  website/logos/transformerlab.svg
  website/logos/unsloth.png
  website/logos/vercel.png
  website/logos/wandb.png
  website/logos/weaviate.png
  website/logos/zenml.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#183 Update logos
  website/data.yml
  website/logos/chroma.png
  website/logos/gateway-api-inference-extension.png
  website/logos/milvus.png
  website/logos/ray.png
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#185 add logo of Chatbot UI and some homepage_url
  website/data.yml
  website/logos/chatbotui.png
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#184 feat: update readme and website automatically
  .github/ISSUE_TEMPLATE/REQUEST.md
  .github/workflows/project-request.yaml
  CONTRIBUTING.md
  project_request.py
  requirements.txt
  website/README.md
  website/data.yml
Labels: lgtm, approved, feature, needs-priority, needs-triage

#187 Add FastGPT to Orchestration/Workflow
  README.md
  website/data.yml
  website/logos/fastgpt.svg
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#191 Add Qwen-Agent to Orchestration/Agent
  README.md
  website/data.yml
  website/logos/qwen-agent.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#193 Add inference-benchmark to Inference/Benchmark
  README.md
  website/data.yml
  website/logos/inference-benchmark.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#194 Update description of Inference Benchmark project
  README.md
  website/data.yml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#200 Add llm to Runtime/Chatbot
  README.md
  website/data.yml
  website/logos/llm.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#206 Change to llm.png to default.png
  website/data.yml
  website/logos/llm.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#208 add https://github.com/crewAIInc/crewAI to Orchestration/Agent category
  README.md
  website/data.yml
  website/logos/crewai.svg
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#204 Add kubectl-ai to Runtime/Chatbot
  README.md
  website/data.yml
  website/logos/kubectl-ai
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#210 Add fast-agent to Orchestration/Agent
  README.md
  website/data.yml
  website/logos/fast-agent.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#205 It is recommended to add a RAG category in the Orchestration director…
  .github/ISSUE_TEMPLATE/REQUEST.md
  README.md
  website/data.yml
  website/logos/ragflow.png
Labels: lgtm, approved, feature, needs-priority, needs-triage

#211 update homepage_urls of DeepSpeed-MII, Ratchet, llmaz and Mooncake
  website/data.yml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#213 Add inference to Inference/Inference Engine
  README.md
  website/data.yml
  website/logos/xinference
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#214 Add inference simulator to inference
  .github/ISSUE_TEMPLATE/REQUEST.md
  website/README.md
  website/data.yml
  website/guide.yml
  website/logos/microsoft.png
  website/settings.yml
Labels: lgtm, approved, feature, needs-priority, needs-triage

#216 Add SWE-agent to Orchestration/Agent
  README.md
  website/data.yml
  website/logos/swe-agent.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#217 Fix logo image
  website/data.yml
  website/logos/anythingllm.jpeg
  website/logos/anythingllm.png
  website/logos/swe-agent.png
  website/logos/swe-agent.svg
Labels: lgtm, approved, cleanup, needs-priority, needs-triage

#218 Add OpenLit to Runtime/observation
  README.md
  website/data.yml
  website/openlit.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#219 move Openlit.png to website/logos
  website/logos/openlit.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#221 Add tinygrad to Inference/Inference Engine
  README.md
  website/data.yml
  website/logos/tinygrad.svg
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#227 Optimize project add script and github action
  .github/ISSUE_TEMPLATE/REQUEST.md
  .github/workflows/project-request.yaml
  project_request.py
Labels: lgtm, approved, feature, needs-priority, needs-triage

#231 Add llm-d to Inference/Inference Platform
  README.md
  website/data.yml
  website/logos/llm-d.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#233 Add magentic-ui to Orchestration/Agent
  README.md
  website/data.yml
  website/logos/magentic-ui
Labels: documentation, lgtm, approved, needs-priority, needs-triage
